on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: demo119.azurecr.io
        username: ${{ secrets.acr_demo119_username }}
        password: ${{ secrets.acr_demo119_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t demo119.azurecr.io/demo1:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push demo119.azurecr.io/demo1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demo1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demo1819a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demo1819a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demo1819a
        container-registry-url: demo119.azurecr.io
        container-registry-username: ${{ secrets.acr_demo119_username }}
        container-registry-password: ${{ secrets.acr_demo119_password }}
        secret-name: demo1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: demo1819a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          demo119.azurecr.io/demo1:${{ github.sha }}
        imagepullsecrets: |
          demo1dockerauth
